import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ScrollTopButton } from "@/components/misc/scroll-top-btn";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Study",
  description: "Generated by create next app.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        id="initial"
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#EAEEFE]`}
      >
        <ScrollTopButton />
        {children}
      </body>
    </html>
  );
}
